# Generated by Django 3.0.3 on 2020-02-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='user_name',
        ),
    ]
